### ISSUE TITLE
Missing filtering and save to list

### ISSUE THREAD

**Issue by linusblom** [chas-academy/10-recipe-app-jonastore#1]
As we said before, I'm now testing 9 and 10 assignments in this repo. But I miss the filtering recipes feature and save/remove recipes to list when logged in.

I can see that you use firebase for authentication. The backend should be build in PHP/Laravel, if you have questions about this talk to Axel and he will help you.

**Comment by axeberg** [comment]
@jonastore

**Comment by jonastore** [comment]
I wasn't aware that php/laravel was a requirement, but I'll change that. As for the filtering, isn't that already there? I mean, you can filter recipes after main ingredient and if they're vegan or not.

**Comment by axeberg** [comment]
@jonastore I think you and I have different definitions of filters. Your "filters" are in fact buttons that trigger a specific search.

A filter is something that "filters" something that's already shown. So for example:

1. I type in "pasta" and hit search.
2. I then click "vegan" to show pasta recipes that are vegan. If none of them are vegan, show "no recipes found matching your criteria". If there are vegan recipes with pasta, show them.

See the bottom example here to see what I mean:

https://vadimdez.github.io/ngx-filter-pipe/

You can see my example here:

- Pipe: https://github.com/chas-academy/tastay/blob/master/src/app/recipes/recipes-pipe.ts
- Loaded: https://github.com/chas-academy/tastay/blob/7ba28cc387870a181f70bee841f16c12cae59ce9/src/app/recipes/recipes.module.ts#L13
- Applied: https://github.com/chas-academy/tastay/blob/185d7127b757d2be9ecb5f935c08192ed4719d9b/src/app/recipes/recipe-list.component.ts#L20

**Comment by axeberg** [comment]
Alright, closing this.
